services:
  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.4.2
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

  worker:
    build:
      context: ./server
      dockerfile: dockerfile.worker
      target: dev
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      REDIS_URL: ${REDIS_URL_WORKER}
      YOUTUBE_ACCESS_TOKEN: ${YOUTUBE_ACCESS_TOKEN}
      LANGSMITH_TRACING: ${LANGSMITH_TRACING}
      LANGSMITH_ENDPOINT: ${LANGSMITH_ENDPOINT}
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
      LANGSMITH_PROJECT: ${LANGSMITH_PROJECT}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

    container_name: worker
    volumes:
      - ./server/src:/app/src
    depends_on:
      - redis
      - db

  api:
    build:
      context: ./server
      dockerfile: dockerfile.api
      target: dev
    container_name: api
    volumes:
      - ./server/src:/app/src
    depends_on:
      - db
      - redis
      - worker
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      REDIS_URL: ${REDIS_URL_API}
    ports:
      - 8080:8080

volumes:
  pgdata:
  redisdata: