FROM python:3.13.3-alpine AS base

WORKDIR /app

COPY poetry.lock .
COPY poetry.toml .
COPY pyproject.toml .

RUN pip install poetry
RUN poetry install

COPY ./src ./src

# === Dev stage ===
FROM base AS dev

RUN pip install debugpy -t /tmp

CMD ["poetry", "run", "python", "/tmp/debugpy", "--listen", "0.0.0.0:6900", "-m", "celery", "-A", "src.worker", "worker", "-l", "DEBUG"]

# === Prod stage ===
FROM base AS prod

CMD ["poetry", "run", "celery", "-A", "src.worker", "worker", "-l", "INFO"]
