FROM python:3.13

WORKDIR /app

# TODO: move code in /src
COPY . .

RUN pip install poetry
RUN poetry install


CMD ["poetry", "run", "fastapi", "dev", "--", "--proxy-headers", "--port", "8080", "--host", "0.0.0.0"]

